### ISSUE TITLE
Zipkin B3 Propagation

### ISSUE THREAD

**Issue by reynaldiwijaya** [jukylin/jaeger-php#16]
Hi are you planning to add support for Zipkin B3 Propagation headers? Will be very useful for integration with service mash. Official Jaeger Client (at least for Go) also has support for this :)

**Comment by jukylin** [comment]
I am learning [istio](https://istio.io/docs/).if necessary, I will support this.

**Comment by reynaldiwijaya** [comment]
Just some update, I managed to create the extractor for Zipkin B3 Propagator, but met a problem where the values needs to be converted to uint64 which is not supported by default by PHP. Need some workaround using pack and unpack to properly convert the hex to int64 (which we will use to send to Jaeger Agent). This is the code which i used

`unpack("J",pack("H*",$value))[1];`

Hope this could help in the future :)

**Comment by jukylin** [comment]
Thinks, It will be useful.

**Comment by jukylin** [comment]
Done #22

**Comment by aogier** [comment]
Hello, this issue still seems open as per #22 changes. I'm working on istio's jaeger too, and when i get a "big" traceid like `acee4e36e5ffa734`, hexdec/sprintf trip still does not produce correct number:

```php
$value = 'acee4e36e5ffa734';
// $value = '7a70cd36dfbfa746';

$dec = hexdec($value);

echo "value: $value\n";
echo "dec: $dec\n";
echo sprintf("output value: %x\n", $dec);
```
produces:
```
value: acee4e36e5ffa734
dec: 1.2460983216675E+19
output value: acee4e36e5ffa800
```

A "smaller" id, like `7a70cd36dfbfa746`, is indeed correctly computed:
```
value: 7a70cd36dfbfa746
dec: 8822777305584609094
output value: 7a70cd36dfbfa746
```

Given that those numbers are in fact a string for our task, why we can't simply cope w/ them as strings w/o this double conversion?

HTH, thanks
